// description of errors can be found on
// https://2captcha.com/2captcha-api#error_handling

enum CAPTCHA_SOLVE_REQUEST_ERRORS {
  ERROR_WRONG_USER_KEY = 'ERROR_WRONG_USER_KEY',
  ERROR_KEY_DOES_NOT_EXIST = 'ERROR_KEY_DOES_NOT_EXIST',
  ERROR_ZERO_BALANCE = 'ERROR_ZERO_BALANCE',
  ERROR_PAGEURL = 'ERROR_PAGEURL',
  ERROR_NO_SLOT_AVAILABLE = 'ERROR_NO_SLOT_AVAILABLE',
  ERROR_IP_NOT_ALLOWED = 'ERROR_IP_NOT_ALLOWED',
  IP_BANNED = 'IP_BANNED',
  ERROR_BAD_TOKEN_OR_PAGEURL = 'ERROR_BAD_TOKEN_OR_PAGE_URL',
  ERROR_GOOGLEKEY = 'ERROR_GOOGLEKEY',
  MAX_USER_TURN = 'MAX_USER_TURN',
  ERROR_BAD_PROXY = 'ERROR_BAD_PROXY'
}

enum CAPTCHA_SOLUTION_QUERY_ERRORS {
  CAPTCHA_NOT_READY = 'CAPCHA_NOT_READY', // misspelled by API
  ERROR_CAPTCHA_UNSOLVABLE = 'ERROR_CAPTCHA_UNSOLVABLE',
  ERROR_WRONG_USER_KEY = 'ERROR_WRONG_USER_KEY',
  ERROR_KEY_DOES_NOT_EXIST = 'ERROR_KEY_DOES_NOT_EXIST',
  ERROR_WRONG_ID_FORMAT = 'ERROR_WRONG_ID_FORMAT',
  ERROR_WRONG_CAPTCHA_ID = 'ERROR_WRONG_CAPTCHA_ID',
  ERROR_EMPTY_ACTION = 'ERROR_EMPTY_ACTION',
  ERROR_PROXY_CONNECTION_FAILED = 'ERROR_PROXY_CONNECTION_FAILED'
}

const API_BASE_URL = 'https://2captcha.com';
const SOLVE_REQUEST_URL = `${API_BASE_URL}/in.php`;
const SOLUTION_QUERY_URL = `${API_BASE_URL}/res.php`;

export {
  CAPTCHA_SOLVE_REQUEST_ERRORS,
  CAPTCHA_SOLUTION_QUERY_ERRORS,
  SOLVE_REQUEST_URL,
  SOLUTION_QUERY_URL
};
