// description of errors can be found on
// https://2captcha.com/2captcha-api#error_handling

enum CAPTCHA_SOLVE_REQUEST_ERRORS {
  ERROR_WRONG_USER_KEY = 'ERROR_WRONG_USER_KEY',
  ERROR_KEY_DOES_NOT_EXIST = 'ERROR_KEY_DOES_NOT_EXIST',
  ERROR_ZERO_BALANCE = 'ERROR_ZERO_BALANCE',
  ERROR_PAGEURL = 'ERROR_PAGEURL',
  ERROR_NO_SLOT_AVAILABLE = 'ERROR_NO_SLOT_AVAILABLE',
  ERROR_IP_NOT_ALLOWED = 'ERROR_IP_NOT_ALLOWED',
  IP_BANNED = 'IP_BANNED',
  ERROR_BAD_TOKEN_OR_PAGEURL = 'ERROR_BAD_TOKEN_OR_PAGE_URL',
  ERROR_GOOGLEKEY = 'ERROR_GOOGLEKEY',
  MAX_USER_TURN = 'MAX_USER_TURN',
  ERROR_BAD_PROXY = 'ERROR_BAD_PROXY'
}

const API_BASE_URL = 'https://2captcha.com';
const SOLVE_REQUEST_URL = `${API_BASE_URL}/in.php`;
const SOLUTION_QUERY_URL = `${API_BASE_URL}/res.php`;

export {
  CAPTCHA_SOLVE_REQUEST_ERRORS,
  SOLVE_REQUEST_URL,
  SOLUTION_QUERY_URL
};
